spring:
  config:
    import:
      - classpath:config/tools/logging.yml    # 기존 "logging" include와 동일
  ai:
    openai:
      api-key: "temp_ai_api_key"
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.0
          maxTokens: 300
      embedding:
        options:
          model: text-embedding-3-small

server:
  tomcat:
    mbeanregistry:
      enabled: true