spring:
  config:
    import:
      - classpath:config/tools/logging.yml    # 기존 "logging" include와 동일
  jpa:
    show-sql: true

security:
  jwt:
    token:
      secret-key: localtestsecretkey
      admin-expire-length: 3600000
      user-expire-length: 604800000