server:
  deploy:
    environment: ${DEPLOY_ENV}
  port: ${PORT:8080}
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    hikari:
      connectionTimeout: '30000'
      maximum-pool-size: '8'
      max-lifetime: '1800000'
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  ai:
    openai:
      api-key: "temp_ai_api_key"
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.0
          maxTokens: 300
      embedding:
        options:
          model: text-embedding-3-small
  mail:
    host: ${MAIL_SMTP_HOST} # smtp 주소
    port: 587 # STMP 서버 포트
    username: ${MAIL_ADDRESS} # 이메일 보내는 용도의 계정
    password: ${MAIL_PASSWORD} # 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # TLS

aws:
  appconfig:
    application: ${AWS_APPCONFIG_APPLICATION}
    environment: ${AWS_APPCONFIG_ENVIRONMENT}
    profile: ${AWS_APPCONFIG_PROFILE}
    region: ${AWS_APPCONFIG_REGION}

springdoc:
  swagger-ui:
    # 각 API의 그룹 표시 순서
    # path, query, body, response 순으로 출력
    groups-order: DESC

    # 태그 정렬 순서.
    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha

    # 컨트롤러 정렬 순서.
    # method는 delete - get - patch - post - put 순으로 정렬된다.
    # alpha를 사용해 알파벳 순으로 정렬할 수 있다.
    operations-sorter: method

    # swagger-ui default url인 petstore html의 비활성화 설정
    disable-swagger-default-url: true

    # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
    display-request-duration: true

  # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  api-docs:
    path: /api-docs

  # Spring Actuator의 endpoint까지 보여줄 것인지?
  show-actuator: true

  # request media type 의 기본 값
  default-consumes-media-type: application/json

  # response media type 의 기본 값
  default-produces-media-type: application/json

  # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
  paths-to-match:
    - /api/v2/**

logging:
  level:
    org:
      apache:
        coyote:
          http11: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      admin-expire-length: ${JWT_ADMIN_EXPIRE_LENGTH}
      user-expire-length: ${JWT_USER_EXPIRE_LENGTH}


notice:
  kuis:
    request-url: https://kuis.konkuk.ac.kr/CmmnOneStop/find.do
    referer-url: https://kuis.konkuk.ac.kr/index.do
  homepage:
    list-url: https://www.konkuk.ac.kr/bbs/{category}/{siteId}/artclList.do
    view-url: https://www.konkuk.ac.kr/bbs/{category}/{siteId}/{noticeId}/artclView.do
  real-estate:
    list-url: http://www.realestate.ac.kr/gb/bbs/board.php?bo_table=notice
    view-url: http://www.realestate.ac.kr/gb/bbs/board.php?bo_table=notice
  recent:
    list-url: https://{department}.konkuk.ac.kr/bbs/{department}/{siteId}/artclList.do
    view-url: https://{department}.konkuk.ac.kr/bbs/{department}/{siteId}/{noticeId}/artclView.do
  normal-base-url: https://old.konkuk.ac.kr/do/MessageBoard/ArticleRead.do
  library:
    request-url: https://library.konkuk.ac.kr/pyxis-api/1/bulletin-boards/1/bulletins
  library-base-url: https://library.konkuk.ac.kr/library-guide/bulletins/notice

auth:
  api-skeleton-producer-url: https://kuis.konkuk.ac.kr/ui/cpr-lib/user-modules.js?p=0.9460032500983822
  password: ${KU_PASSWORD}
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38
  id: ${KU_ID}
  session: JSESSIONID=00015GJS2T_gl7M-TqGjYvyHAuJ:-103KQM
  referer: https://kuis.konkuk.ac.kr/index.do
  login-url: https://kuis.konkuk.ac.kr/Login/login.do

firebase:
  file-path: third/ku-stack-firebase-adminsdk-87nwq-ae6a2df931.json

admin:
  password: ${ADMIN_PASSWORD}
  id: ${ADMIN_ID}

ip:
  proxy-list: 14.63.228.239:80, 101.79.15.198:80, 222.104.128.205:8678, 106.244.154.91:8080, 103.51.205.42:8181

staff:
  each-dept-url: https://{department}.konkuk.ac.kr/{department}/{siteId}/subview.do
