INSERT INTO category (name)
SELECT 'BACHELOR' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'BACHELOR');

INSERT INTO category (name)
SELECT 'SCHOLARSHIP' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'SCHOLARSHIP');

INSERT INTO category (name)
SELECT 'EMPLOYMENT' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'EMPLOYMENT');

INSERT INTO category (name)
SELECT 'NATIONAL' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'NATIONAL');

INSERT INTO category (name)
SELECT 'STUDENT' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'STUDENT');

INSERT INTO category (name)
SELECT 'INDUSTRY_UNIVERSITY' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'INDUSTRY_UNIVERSITY');

INSERT INTO category (name)
SELECT 'NORMAL' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'NORMAL');

INSERT INTO category (name)
SELECT 'LIBRARY' FROM DUAL WHERE NOT EXISTS(SELECT * FROM category WHERE name = 'LIBRARY');
