spring:
  ai:
    openai:
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_CHAT_MODEL}
          temperature: 0.0
          maxTokens: 1000
      embedding:
        options:
          model: ${AI_EMBEDDING_MODEL}
    vectorstore:
      chroma:
        client:
          key-token: ${CHROMA_API_KEY}
        store:
          collection-name: ${CHROMA_COLLECTION_NAME}