spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    hikari:
      connectionTimeout: '30000'
      maximum-pool-size: '8'
      max-lifetime: '1800000'
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}